# Try rendering existing gabc scores with lilygabc en masse

file 'psalter.ly' => [__FILE__] do |t|
  # list the gabc files in the same order they are typeset
  # in the psalter booklet, so it's easy to compare
  # Gregorio and LilyPond rendering
  str =
    "\\include \"lilygabc.ily\"\n" +
    "\\layout { \\lilygabcModernGregorianStemlessLayout }\n" +
    File
      .read('../libelli/psalterium.tex')
      .scan(/\\gregorioscore\{(.+?)\}|\\(sub)?section\*?\{(.+?)\}/)
      .collect do |i|
    if i[0]
      "\\score { \\gabc-file \"../libelli/#{i[0].sub('.gtex', '.gabc')}\" }"
    elsif i[2]
      (i[1] ? "" : "\\pageBreak\n") +
        "\\markup\\large{#{i[2]}}"
    end
  end.join("\n")

  File.write t.name, str
end

file 'psalter_vaticana.ly' => ['psalter.ly', 'vaticana_settings.ly', __FILE__] do |t|
  sh "echo '\\include \"gregorian.ly\"' > #{t.name}"
  sh "cat vaticana_settings.ly >> #{t.name}"
  sh "sed s/gabc-file/gabc-vaticana-file/ #{t.prerequisites[0]} | " +
     "grep --invert-match layout " +
     " >> #{t.name}"
end

lilypond = lambda do |task, _|
  libdir = ENV['LILY_LIBDIR'] ||
           raise('ERROR: Environment variable LILY_LIBDIR not found. It should be set to point to the location of the "lilygabc" package.')

  sh 'lilypond', "--include=#{libdir}", task.prerequisites[0]
end

file 'psalter.pdf' => ['psalter.ly'], &lilypond
file 'psalter_vaticana.pdf' => ['psalter_vaticana.ly'], &lilypond

task default: 'psalter.pdf'
